# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
### [your code here]
import numpy as np




### 2. Print the NUMPY version and the configuration.


In [3]:
### [your code here]
print(np.__version__)

2.1.3


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [7]:
### [your code here]
a = np.random.random((2, 3, 5))



### 4. Print a.


In [9]:
### [your code here]
print("a =", a)

a = [[[0.41507184 0.5768164  0.77727865 0.46891815 0.98708963]
  [0.28826202 0.35456274 0.63460409 0.43106393 0.8886203 ]
  [0.50983235 0.79243129 0.54974881 0.58224754 0.30232343]]

 [[0.73847175 0.24983658 0.93796212 0.86101346 0.5490756 ]
  [0.19517418 0.9321514  0.56843413 0.90480082 0.44349187]
  [0.78696664 0.1519602  0.20016868 0.33750235 0.51856528]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [20]:
### [your code here]
b = np.ones((5, 3, 2)) 


### 6. Print b.


In [21]:
### [your code here]

print("b = ", b)

b =  [[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [39]:
### [your code here]

print("The a and b tensors have different sizes.")

print("The size of a is:", np.shape(a))
print("The size of b is:", np.shape(b))

The a and b tensors have different sizes.
The size of a is: (2, 3, 5)
The size of b is: (5, 3, 2)


### 8. Are you able to add a and b? Why or why not?


In [42]:
### [your code here]

print("The a and b tensors have different sizes; trying to add a and b will raise a ValueError; addition works for tensors that have the same size.")

z = a + b # ValueError: operands could not be broadcast together with shapes (2,3,5) (5,3,2)  

The a and b tensors have different sizes; trying to add a and b will raise a ValueError; addition works for tensors that have the same size.


ValueError: operands could not be broadcast together with shapes (2,3,5) (5,3,2) 



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [28]:
### [your code here]

c = np.transpose(b)


### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [44]:
### [your code here]

print("The size of a is:", np.shape(a))
print("The size of c is:", np.shape(c))
print("The sizes of a and c is the same. Adding them will work.")

d = a + c

print("The Sum of a and the b(T) is:", d)

The size of a is: (2, 3, 5)
The size of c is: (2, 3, 5)
The sizes of a and c is the same. Adding them will work.
The Sum of a and the b(T) is: [[[1.41507184 1.5768164  1.77727865 1.46891815 1.98708963]
  [1.28826202 1.35456274 1.63460409 1.43106393 1.8886203 ]
  [1.50983235 1.79243129 1.54974881 1.58224754 1.30232343]]

 [[1.73847175 1.24983658 1.93796212 1.86101346 1.5490756 ]
  [1.19517418 1.9321514  1.56843413 1.90480082 1.44349187]
  [1.78696664 1.1519602  1.20016868 1.33750235 1.51856528]]]



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [53]:
### [your code here]

print("a = ", a)
print("d = ", d)

print("Addition: As the b/c tensor was full with 1, the d tensor has all the values equal with the corresponding value of a tensor plus 1.")

a =  [[[0.41507184 0.5768164  0.77727865 0.46891815 0.98708963]
  [0.28826202 0.35456274 0.63460409 0.43106393 0.8886203 ]
  [0.50983235 0.79243129 0.54974881 0.58224754 0.30232343]]

 [[0.73847175 0.24983658 0.93796212 0.86101346 0.5490756 ]
  [0.19517418 0.9321514  0.56843413 0.90480082 0.44349187]
  [0.78696664 0.1519602  0.20016868 0.33750235 0.51856528]]]
d =  [[[1.41507184 1.5768164  1.77727865 1.46891815 1.98708963]
  [1.28826202 1.35456274 1.63460409 1.43106393 1.8886203 ]
  [1.50983235 1.79243129 1.54974881 1.58224754 1.30232343]]

 [[1.73847175 1.24983658 1.93796212 1.86101346 1.5490756 ]
  [1.19517418 1.9321514  1.56843413 1.90480082 1.44349187]
  [1.78696664 1.1519602  1.20016868 1.33750235 1.51856528]]]
Addition: As the b/c tensor was full with 1, the d tensor has all the values equal with the corresponding value of a tensor plus 1.



### 12. Multiply a and c. Assign the result to e.


In [48]:
### [your code here]

e = a * c




### 13. Does e equal to a? Why or why not?


In [55]:
### [your code here]

print("a =", a)
print("e =", e)

print("Multiplication: As the b/c tensor was full with 1, the e tensor has all the values equal with the corresponding value of a tensor: value * 1 = value.")


a = [[[0.41507184 0.5768164  0.77727865 0.46891815 0.98708963]
  [0.28826202 0.35456274 0.63460409 0.43106393 0.8886203 ]
  [0.50983235 0.79243129 0.54974881 0.58224754 0.30232343]]

 [[0.73847175 0.24983658 0.93796212 0.86101346 0.5490756 ]
  [0.19517418 0.9321514  0.56843413 0.90480082 0.44349187]
  [0.78696664 0.1519602  0.20016868 0.33750235 0.51856528]]]
e = [[[0.41507184 0.5768164  0.77727865 0.46891815 0.98708963]
  [0.28826202 0.35456274 0.63460409 0.43106393 0.8886203 ]
  [0.50983235 0.79243129 0.54974881 0.58224754 0.30232343]]

 [[0.73847175 0.24983658 0.93796212 0.86101346 0.5490756 ]
  [0.19517418 0.9321514  0.56843413 0.90480082 0.44349187]
  [0.78696664 0.1519602  0.20016868 0.33750235 0.51856528]]]
Multiplication: As the b/c tensor was full with 1, the e tensor has all the values equal with the corresponding value of a tensor: value * 1 = value.




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [56]:
### [your code here]

d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print("d_min = ", d_min)
print("d_max = ", d_max)
print("d_mean = ", d_mean)

d_min =  1.1519602006772598
d_max =  1.9870896307472532
d_mean =  1.564481540787587



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [58]:
### [your code here]

f = np.empty(np.shape(d))

print("The size of f is:", np.shape(f))

The size of f is: (2, 3, 5)





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [70]:
### [your code here]

def fill_f(d, f):
    d_max = np.max(d)
    d_min = np.min(d)
    d_mean = np.mean(d)

    for i in range(np.shape(d)[0]):
        for j in range(np.shape(d)[1]):
            for k in range(np.shape(d)[2]):
                if d[i][j][k] > d_min and d[i][j][k] < d_mean:
                    f[i][j][k] = 25
                elif d[i][j][k] > d_mean and d[i][j][k] < d_max:
                    f[i][j][k] = 75
                elif d[i][j][k] == d_mean:
                    f[i][j][k] = 50
                elif d[i][j][k] == d_min:
                    f[i][j][k] = 0
                elif d[i][j][k] == d_max:
                    f[i][j][k] = 100
    return f

f = fill_f(d, f)





### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [71]:
### [your code here]

print("d = ", d)
print("f = ", f)

dd = ([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

ff = np.empty(np.shape(dd))
ff = fill_f(dd, ff)
print("dd = ", dd)
print("ff = ", ff)

d =  [[[1.41507184 1.5768164  1.77727865 1.46891815 1.98708963]
  [1.28826202 1.35456274 1.63460409 1.43106393 1.8886203 ]
  [1.50983235 1.79243129 1.54974881 1.58224754 1.30232343]]

 [[1.73847175 1.24983658 1.93796212 1.86101346 1.5490756 ]
  [1.19517418 1.9321514  1.56843413 1.90480082 1.44349187]
  [1.78696664 1.1519602  1.20016868 1.33750235 1.51856528]]]
f =  [[[ 25.  75.  75.  25. 100.]
  [ 25.  25.  75.  25.  75.]
  [ 25.  75.  25.  75.  25.]]

 [[ 75.  25.  75.  75.  25.]
  [ 25.  75.  75.  75.  25.]
  [ 75.   0.  25.  25.  25.]]]
dd =  [[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931], [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981], [1.72201435, 1.1862918, 1.87078449, 1.7726778, 1.88180042]], [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381], [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881], [1.18068344, 1.9587381, 1.00656599, 1.93402165, 1.73514584]]]
ff =  [[[ 75.  75.  75.  25.  75.]
  [ 75.  75.  25.  25.  25.]
  [ 75.  2

### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [79]:
### [your code here]

def fill_f_2(d, f):
    d_max = np.max(d)
    d_min = np.min(d)
    d_mean = np.mean(d)

    for i in range(np.shape(d)[0]):
        for j in range(np.shape(d)[1]):
            for k in range(np.shape(d)[2]):
                if d[i][j][k] > d_min and d[i][j][k] < d_mean:
                    f[i][j][k] = 'B'
                elif d[i][j][k] > d_mean and d[i][j][k] < d_max:
                    f[i][j][k] = 'D'
                elif d[i][j][k] == d_mean:
                    f[i][j][k] = 'C'
                elif d[i][j][k] == d_min:
                    f[i][j][k] = 'A'
                elif d[i][j][k] == d_max:
                    f[i][j][k] = 'E'
    return f


ff2 = np.empty(np.shape(dd), dtype='U1')
ff2 = fill_f_2(dd, ff2)
print("dd = ", dd)
print("ff2 = ", ff2)

dd =  [[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931], [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981], [1.72201435, 1.1862918, 1.87078449, 1.7726778, 1.88180042]], [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381], [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881], [1.18068344, 1.9587381, 1.00656599, 1.93402165, 1.73514584]]]
ff2 =  [[['D' 'D' 'D' 'B' 'D']
  ['D' 'D' 'B' 'B' 'B']
  ['D' 'B' 'D' 'D' 'D']]

 [['B' 'B' 'B' 'B' 'E']
  ['D' 'D' 'D' 'D' 'D']
  ['B' 'D' 'A' 'D' 'D']]]
